from dna_toolset.bio_seq import BioSeq

test_dna = BioSeq("ATCGTGT", "RNA", "Test Data")
print("")
print(test_dna.get_seq_info())
print("")
test_dna.generate_rand_seq(20)
print(test_dna.get_seq_info())
print(test_dna.get_seq_biotype())
print(test_dna.count_nucleotides())
print(test_dna.transcription())
print(test_dna.reverse_compliment())
print(test_dna.gc_content(test_dna.seq))
print(test_dna.gc_content_subsection(test_dna.seq, 4))
print(test_dna.translate_seq())
